# This file was generated by GoReleaser. DO NOT EDIT.
cask "hone" do
  version "1.2.2"

  on_macos do
    on_intel do
      url "https://github.com/pricklywiggles/hone/releases/download/v#{version}/hone_#{version}_darwin_amd64.tar.gz"
      sha256 "ac9de4dca9256f914e1011076587988741435adc079db73242c4f77266f3a76e"
    end
    on_arm do
      url "https://github.com/pricklywiggles/hone/releases/download/v#{version}/hone_#{version}_darwin_arm64.tar.gz"
      sha256 "e0b2581a2c04cf659528eb3da7207fcbdb0a42897cb43e344b7ed898be789340"
    end
  end

  name "hone"
  desc "Practice coding problems with spaced repetition"
  homepage "https://pricklywiggles.github.io/hone"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hone"

  # No zap stanza required

end
