# This file was generated by GoReleaser. DO NOT EDIT.
cask "hone" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/pricklywiggles/hone/releases/download/v#{version}/hone_#{version}_darwin_amd64.tar.gz"
      sha256 "5371fac95250748c7fe3bd0d4db022a6f23d4e4a332a3b07347b90168aa13e74"
    end
    on_arm do
      url "https://github.com/pricklywiggles/hone/releases/download/v#{version}/hone_#{version}_darwin_arm64.tar.gz"
      sha256 "ef1c9ed97be62c766afc775e77f0ac98a266ba69ccb846e39c2d5eecc2c4a245"
    end
  end

  name "hone"
  desc "Practice coding problems with spaced repetition"
  homepage "https://pricklywiggles.github.io/hone"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hone"

  # No zap stanza required

end
