# This file was generated by GoReleaser. DO NOT EDIT.
cask "hone" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/pricklywiggles/hone/releases/download/v#{version}/hone_#{version}_darwin_amd64.tar.gz"
      sha256 "142ff5eb392c1b5ef85ece23c45f8cff6a7d224e7783c90f695af8fe7637a955"
    end
    on_arm do
      url "https://github.com/pricklywiggles/hone/releases/download/v#{version}/hone_#{version}_darwin_arm64.tar.gz"
      sha256 "6c0117e13af57df2a78c1e240516ca93e1cf21d63d38e8d39137d15e0af72389"
    end
  end

  name "hone"
  desc "Practice coding problems with spaced repetition"
  homepage "https://pricklywiggles.github.io/hone"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hone"

  # No zap stanza required

end
